[package]
name = "optibriumWebService"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
redis = { version = "0.27.5", features = ["tokio-comp"] }
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
